validate required environment variables in CI build

diff --git a/.github/workflows/custom-ci-artifacts.yml b/.github/workflows/custom-ci-artifacts.yml
--- a/.github/workflows/custom-ci-artifacts.yml
+++ b/.github/workflows/custom-ci-artifacts.yml
@@ -61,13 +61,16 @@ jobs:
 
       - name: Build
         env:
-          CUSTOM_JP_PLATFORM_NAME: ${{ vars.CUSTOM_JP_PLATFORM_NAME || 'Tuxxxチャット' }}
-          CUSTOM_PLATFORM_NAME: ${{ vars.CUSTOM_PLATFORM_NAME || 'TuxxxChat' }}
-          CUSTOM_SERVICE_NAME: ${{ vars.CUSTOM_SERVICE_NAME || 'Tuxxx' }}
+          CUSTOM_JP_PLATFORM_NAME: ${{ vars.CUSTOM_JP_PLATFORM_NAME }}
+          CUSTOM_PLATFORM_NAME: ${{ vars.CUSTOM_PLATFORM_NAME }}
+          CUSTOM_SERVICE_NAME: ${{ vars.CUSTOM_SERVICE_NAME }}
         run: |
-          echo "CUSTOM_JP_PLATFORM_NAME=${CUSTOM_JP_PLATFORM_NAME}"
-          echo "CUSTOM_PLATFORM_NAME=${CUSTOM_PLATFORM_NAME}"
-          echo "CUSTOM_SERVICE_NAME=${CUSTOM_SERVICE_NAME}"
+          required_envs=( "CUSTOM_JP_PLATFORM_NAME" "CUSTOM_PLATFORM_NAME" "CUSTOM_SERVICE_NAME" )
+          for env_name in "${required_envs[@]}"; do
+            env_value="${!env_name}"
+            [ -z "$env_value" ] && { echo "::error title=Environment Variable Check Error::'$env_name' is not set."; exit 1; }
+          done
+
           make config-reset
           make build-cmd BUILD_NUMBER='${GITHUB_HEAD_REF}-${GITHUB_RUN_ID}'
           make customize-assets
